<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260403111408 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Remove TransplantType, change User name/surname/cristal_id from encrypted TEXT to plain VARCHAR(255)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE transplant DROP CONSTRAINT fk_e522b45ab8805c1');
        $this->addSql('DROP INDEX idx_e522b45ab8805c1');
        $this->addSql('ALTER TABLE transplant DROP transplant_type_id');
        $this->addSql('DROP TABLE ref_transplant_type');
        $this->addSql('ALTER TABLE "user" ALTER name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE "user" ALTER surname TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE "user" ALTER cristal_id TYPE VARCHAR(255)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ref_transplant_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL, is_active BOOLEAN NOT NULL, display_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_b97a371277153098 ON ref_transplant_type (code)');
        $this->addSql('ALTER TABLE transplant ADD transplant_type_id INT NOT NULL');
        $this->addSql('ALTER TABLE transplant ADD CONSTRAINT fk_e522b45ab8805c1 FOREIGN KEY (transplant_type_id) REFERENCES ref_transplant_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_e522b45ab8805c1 ON transplant (transplant_type_id)');
        $this->addSql('ALTER TABLE "user" ALTER name TYPE TEXT');
        $this->addSql('ALTER TABLE "user" ALTER surname TYPE TEXT');
        $this->addSql('ALTER TABLE "user" ALTER cristal_id TYPE TEXT');
    }
}
