<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260310084153 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE patient_authorized_user (patient_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (patient_id, user_id))');
        $this->addSql('CREATE INDEX IDX_57C237346B899279 ON patient_authorized_user (patient_id)');
        $this->addSql('CREATE INDEX IDX_57C23734A76ED395 ON patient_authorized_user (user_id)');
        $this->addSql('ALTER TABLE patient_authorized_user ADD CONSTRAINT FK_57C237346B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE patient_authorized_user ADD CONSTRAINT FK_57C23734A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE login_activity ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE login_activity ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN login_activity.created_at IS \'\'');
        $this->addSql('ALTER TABLE patient ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE patient ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN patient.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN patient.updated_at IS \'\'');
        $this->addSql('ALTER INDEX uniq_patient_file_number RENAME TO UNIQ_1ADAD7EB2E8739EB');
        $this->addSql('ALTER TABLE "user" ADD is_chu_practitioner BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER created_at DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN "user".last_login_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE patient_authorized_user DROP CONSTRAINT FK_57C237346B899279');
        $this->addSql('ALTER TABLE patient_authorized_user DROP CONSTRAINT FK_57C23734A76ED395');
        $this->addSql('DROP TABLE patient_authorized_user');
        $this->addSql('ALTER TABLE login_activity ALTER id SET DEFAULT nextval(\'login_activity_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE login_activity ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN login_activity.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE patient ALTER id SET DEFAULT nextval(\'patient_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE patient ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN patient.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN patient.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX uniq_1adad7eb2e8739eb RENAME TO uniq_patient_file_number');
        $this->addSql('ALTER TABLE "user" DROP is_chu_practitioner');
        $this->addSql('ALTER TABLE "user" ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('COMMENT ON COLUMN "user".last_login_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'(DC2Type:datetime_immutable)\'');
    }
}
