<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260327130804 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, message VARCHAR(500) NOT NULL, is_read BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, recipient_id INT NOT NULL, triggered_by_id INT DEFAULT NULL, related_patient_id INT DEFAULT NULL, related_donor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAE92F8F78 ON notification (recipient_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CA63C5923F ON notification (triggered_by_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CAE1449AC9 ON notification (related_patient_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CA9B54F90A ON notification (related_donor_id)');
        $this->addSql('CREATE INDEX idx_notification_recipient_read ON notification (recipient_id, is_read)');
        $this->addSql('CREATE INDEX idx_notification_created ON notification (created_at)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAE92F8F78 FOREIGN KEY (recipient_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA63C5923F FOREIGN KEY (triggered_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAE1449AC9 FOREIGN KEY (related_patient_id) REFERENCES patient (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA9B54F90A FOREIGN KEY (related_donor_id) REFERENCES donor (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAE92F8F78');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA63C5923F');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAE1449AC9');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA9B54F90A');
        $this->addSql('DROP TABLE notification');
    }
}
