<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260310100543 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE biological_result (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, creatinine DOUBLE PRECISION DEFAULT NULL, creatinine_clearance DOUBLE PRECISION DEFAULT NULL, proteinuria DOUBLE PRECISION DEFAULT NULL, hemoglobin DOUBLE PRECISION DEFAULT NULL, white_blood_cells DOUBLE PRECISION DEFAULT NULL, platelets DOUBLE PRECISION DEFAULT NULL, tacrolimus_level DOUBLE PRECISION DEFAULT NULL, ciclosporin_level DOUBLE PRECISION DEFAULT NULL, cmv_pcr VARCHAR(20) DEFAULT NULL, ebv_pcr VARCHAR(20) DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E5FB69886B899279 ON biological_result (patient_id)');
        $this->addSql('CREATE TABLE consultation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, practitioner_name VARCHAR(100) NOT NULL, type VARCHAR(50) NOT NULL, observations TEXT NOT NULL, treatment_notes TEXT DEFAULT NULL, next_appointment_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_964685A66B899279 ON consultation (patient_id)');
        $this->addSql('CREATE TABLE medical_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, description TEXT NOT NULL, diagnosis_date DATE DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_61B890856B899279 ON medical_history (patient_id)');
        $this->addSql('CREATE TABLE therapeutic_education (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_date DATE NOT NULL, topic VARCHAR(100) NOT NULL, educator VARCHAR(100) NOT NULL, objectives TEXT DEFAULT NULL, observations TEXT DEFAULT NULL, patient_progress VARCHAR(20) DEFAULT NULL, next_session_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_17995B086B899279 ON therapeutic_education (patient_id)');
        $this->addSql('ALTER TABLE biological_result ADD CONSTRAINT FK_E5FB69886B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A66B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE medical_history ADD CONSTRAINT FK_61B890856B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE therapeutic_education ADD CONSTRAINT FK_17995B086B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE biological_result DROP CONSTRAINT FK_E5FB69886B899279');
        $this->addSql('ALTER TABLE consultation DROP CONSTRAINT FK_964685A66B899279');
        $this->addSql('ALTER TABLE medical_history DROP CONSTRAINT FK_61B890856B899279');
        $this->addSql('ALTER TABLE therapeutic_education DROP CONSTRAINT FK_17995B086B899279');
        $this->addSql('DROP TABLE biological_result');
        $this->addSql('DROP TABLE consultation');
        $this->addSql('DROP TABLE medical_history');
        $this->addSql('DROP TABLE therapeutic_education');
    }
}
