<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260313131411 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE transplant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, transplant_date DATE NOT NULL, rank SMALLINT NOT NULL, donor_type VARCHAR(30) NOT NULL, is_graft_functional BOOLEAN NOT NULL, graft_end_date DATE DEFAULT NULL, graft_end_cause TEXT DEFAULT NULL, transplant_type VARCHAR(50) NOT NULL, surgeon_name VARCHAR(100) DEFAULT NULL, declamping_date DATE DEFAULT NULL, declamping_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, harvest_side VARCHAR(10) NOT NULL, transplant_side VARCHAR(10) NOT NULL, peritoneal_position VARCHAR(20) NOT NULL, total_ischemia_minutes INT NOT NULL, anastomosis_duration INT NOT NULL, jj_probe BOOLEAN NOT NULL, comment TEXT DEFAULT NULL, operative_report_filename VARCHAR(255) DEFAULT NULL, cmv_status VARCHAR(10) NOT NULL, ebv_status VARCHAR(10) DEFAULT NULL, toxoplasmosis_status VARCHAR(5) DEFAULT NULL, hla_a SMALLINT NOT NULL, hla_b SMALLINT NOT NULL, hla_cw SMALLINT DEFAULT NULL, hla_dr SMALLINT NOT NULL, hla_dq SMALLINT NOT NULL, hla_dp SMALLINT DEFAULT NULL, immunological_risk VARCHAR(30) NOT NULL, immunosuppressive_conditioning JSON NOT NULL, dialysis BOOLEAN NOT NULL, last_dialysis_date DATE DEFAULT NULL, has_protocol BOOLEAN NOT NULL, protocol_filename VARCHAR(255) DEFAULT NULL, donor_data JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, patient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_transplant_patient ON transplant (patient_id)');
        $this->addSql('ALTER TABLE transplant ADD CONSTRAINT FK_E522B45A6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE transplant DROP CONSTRAINT FK_E522B45A6B899279');
        $this->addSql('DROP TABLE transplant');
    }
}
