<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260327081949 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Replace patient_authorized_user join table with patient_access entity (primary/secondary access levels)';
    }

    public function up(Schema $schema): void
    {
        // Create the new patient_access table
        $this->addSql('CREATE TABLE patient_access (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, access_level VARCHAR(20) NOT NULL, granted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, user_id INT NOT NULL, granted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D27C2AE6B899279 ON patient_access (patient_id)');
        $this->addSql('CREATE INDEX IDX_D27C2AEA76ED395 ON patient_access (user_id)');
        $this->addSql('CREATE INDEX IDX_D27C2AE3151C11F ON patient_access (granted_by_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_patient_user ON patient_access (patient_id, user_id)');
        $this->addSql('ALTER TABLE patient_access ADD CONSTRAINT FK_D27C2AE6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patient_access ADD CONSTRAINT FK_D27C2AEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patient_access ADD CONSTRAINT FK_D27C2AE3151C11F FOREIGN KEY (granted_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');

        // Migrate existing data: first user per patient becomes primary, rest secondary
        $this->addSql(<<<'SQL'
            INSERT INTO patient_access (patient_id, user_id, access_level, granted_at)
            SELECT pau.patient_id, pau.user_id,
                CASE WHEN pau.user_id = first_user.first_user_id THEN 'primary' ELSE 'secondary' END,
                NOW()
            FROM patient_authorized_user pau
            JOIN (
                SELECT patient_id, MIN(user_id) AS first_user_id
                FROM patient_authorized_user
                GROUP BY patient_id
            ) first_user ON pau.patient_id = first_user.patient_id
        SQL);

        // Drop old join table
        $this->addSql('ALTER TABLE patient_authorized_user DROP CONSTRAINT fk_57c23734a76ed395');
        $this->addSql('ALTER TABLE patient_authorized_user DROP CONSTRAINT fk_57c237346b899279');
        $this->addSql('DROP TABLE patient_authorized_user');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE patient_authorized_user (patient_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (patient_id, user_id))');
        $this->addSql('CREATE INDEX idx_57c23734a76ed395 ON patient_authorized_user (user_id)');
        $this->addSql('CREATE INDEX idx_57c237346b899279 ON patient_authorized_user (patient_id)');
        $this->addSql('ALTER TABLE patient_authorized_user ADD CONSTRAINT fk_57c23734a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient_authorized_user ADD CONSTRAINT fk_57c237346b899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient_access DROP CONSTRAINT FK_D27C2AE6B899279');
        $this->addSql('ALTER TABLE patient_access DROP CONSTRAINT FK_D27C2AEA76ED395');
        $this->addSql('ALTER TABLE patient_access DROP CONSTRAINT FK_D27C2AE3151C11F');
        $this->addSql('DROP TABLE patient_access');
    }
}
