<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260320153917 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE break_the_glass_access (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, justification TEXT NOT NULL, accessed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reviewed BOOLEAN DEFAULT false NOT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, patient_id INT NOT NULL, reviewed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_374A1DDEA76ED395 ON break_the_glass_access (user_id)');
        $this->addSql('CREATE INDEX IDX_374A1DDE6B899279 ON break_the_glass_access (patient_id)');
        $this->addSql('CREATE INDEX IDX_374A1DDEFC6B21F1 ON break_the_glass_access (reviewed_by_id)');
        $this->addSql('CREATE INDEX idx_btg_user_patient ON break_the_glass_access (user_id, patient_id)');
        $this->addSql('CREATE INDEX idx_btg_expires ON break_the_glass_access (expires_at)');
        $this->addSql('CREATE INDEX idx_btg_accessed ON break_the_glass_access (accessed_at)');
        $this->addSql('ALTER TABLE break_the_glass_access ADD CONSTRAINT FK_374A1DDEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE break_the_glass_access ADD CONSTRAINT FK_374A1DDE6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE break_the_glass_access ADD CONSTRAINT FK_374A1DDEFC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE break_the_glass_access DROP CONSTRAINT FK_374A1DDEA76ED395');
        $this->addSql('ALTER TABLE break_the_glass_access DROP CONSTRAINT FK_374A1DDE6B899279');
        $this->addSql('ALTER TABLE break_the_glass_access DROP CONSTRAINT FK_374A1DDEFC6B21F1');
        $this->addSql('DROP TABLE break_the_glass_access');
    }
}
